apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bluelotusfoods-api
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: PROJECT_ID-compute@developer.gserviceaccount.com
      containers:
      - name: bluelotusfoods-api
        image: us-central1-docker.pkg.dev/PROJECT_ID/bluelotusfoods/bluelotusfoods-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DB_HOST
          value: "YOUR_DB_HOST"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "bluelotusfoods"
        - name: DB_USER
          value: "blf_user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-password
        - name: EMAIL_SERVICE_URL
          value: "https://bluelotusfoods-email-PROJECT_ID.a.run.app"
        - name: CORS_ORIGINS
          value: '["https://www.thebluelotusfoods.com"]'
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 10
  traffic:
  - percent: 100
    latestRevision: true
