services:
  - type: web
    name: bluelotusfoods-api
    env: docker
    rootDir: bluelotusfoods-api
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: EMAIL_SERVICE_URL
        value: https://bluelotusfoods-email.onrender.com
      - key: CORS_ORIGINS
        value: '["https://www.thebluelotusfoods.com"]'
  - type: web
    name: bluelotusfoods-email
    env: docker
    rootDir: bluelotusfoods-email
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: Blue Lotus Foods
      - key: EMAIL_SIMULATION_MODE
        value: "false"
